spring:
  application:
    name: spring-cloud-gateway-mini
  cloud:
    gateway:
      mini:
        httpclient:
          connectTimeout: 1000
          responseTimeout: 5000
  config:
    import: optional:consul:localhost:8500